# Generated by Django 5.1.2 on 2024-10-30 18:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogindexpage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Post date'),
        ),
    ]
